// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ItemInput$ReactHooksTemplate = require("./ItemInput.bs.js");

var initialList = /* array */[];

function App$ShoppingList(Props) {
  return React.createElement("div", undefined, React.createElement(ItemInput$ReactHooksTemplate.make, { }));
}

var ShoppingList = /* module */[
  /* initialList */initialList,
  /* make */App$ShoppingList
];

exports.ShoppingList = ShoppingList;
/* react Not a pure module */
