// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ItemInput$ReactHooksTemplate = require("./ItemInput.bs.js");
var Component2$ReactHooksTemplate = require("./Component2.bs.js");

var items = /* array */[];

ReactDOMRe.renderToElementWithId(React.createElement(ItemInput$ReactHooksTemplate.make, { }), "item-input");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$ReactHooksTemplate.make, {
          greeting: "Hello!"
        }), "index2");

exports.items = items;
/*  Not a pure module */
