// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ShoppingList$ReactHooksTemplate = require("./ShoppingList.bs.js");

var initialList = /* record */[/* items : array */[]];

ReactDOMRe.renderToElementWithId(React.createElement(ShoppingList$ReactHooksTemplate.make, {
          shoppingList: initialList
        }), "shopping-list");

exports.initialList = initialList;
/*  Not a pure module */
