// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function handleClick(_event) {
  console.log("clicked!");
  return /* () */0;
}

function ItemInput(Props) {
  return React.createElement("div", {
              className: "item-input"
            }, React.createElement("input", {
                  className: "item-input__input"
                }), React.createElement("div", {
                  onClick: handleClick
                }));
}

var make = ItemInput;

exports.handleClick = handleClick;
exports.make = make;
/* react Not a pure module */
