// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ItemInput$ReactHooksTemplate = require("./ItemInput.bs.js");

function ShoppingList(Props) {
  Props.shoppingList;
  return React.createElement("div", undefined, React.createElement(ItemInput$ReactHooksTemplate.make, { }));
}

var make = ShoppingList;

exports.make = make;
/* react Not a pure module */
